.vscode/launch.json, README.md, src/app/app.component.html, src/assets/styles/components/feature-block.scss, src/assets/styles/header.scss
(part of my familiarization with code base and tools)
=> cleaned up some classes and css

.gitignore, .vscode/launch.json, src/app/app.module.ts, src/app/applications/application-detail-resolver.service.ts, src/app/applications/application-detail/application-detail.component.html, src/app/applications/application-detail/application-detail.component.ts, src/app/applications/application-list/application-list.component.html, src/app/applications/applications-routing.module.ts, src/app/applications/applications.module.ts, src/app/home/home.component.html, src/app/home/home.component.ts, src/app/map/config/map-config.service.ts, src/app/map/main-map/main-map.component.ts, src/app/map/map.module.ts, src/app/models/application.ts, src/app/models/search.ts, src/app/search/search.component.ts, src/app/services/api.ts, src/app/services/application.service.spec.ts, src/app/services/application.service.ts, src/app/services/document.service.ts
=> cleanup of application, routes, model, etc

.vscode/launch.json, src/app/applications/application-detail/application-detail.component.html, src/app/applications/application-list/application-list.component.html, src/app/applications/application-list/application-list.component.scss, src/app/models/application.ts, src/assets/styles/components/hero-banner.scss, src/assets/styles/header.scss, src/index.html
removed code from application + updated some model types
moved map into legal desc section
added padding to push body below fixed header + updated banner background image responsive position and size
=> DEBUG: misc cleanup before further dev

src/app/applications/application-list/application-list.component.ts, src/app/services/api.ts, src/app/services/application.service.ts
plus work-around for change detection bug
=> PRC-113: use stage code to determine application status

src/app/applications/application-detail/add-comment/add-comment.component.scss, src/app/applications/application-detail/application-detail.component.html, src/app/applications/application-detail/application/application-tab-content.component.html, src/app/applications/application-detail/application/application-tab-content.component.ts, src/app/applications/application-detail/comments/comments-tab-content.component.html, src/app/applications/application-detail/comments/comments-tab-content.component.scss, src/app/applications/application-detail/comments/comments-tab-content.component.ts, src/app/applications/application-detail/comments/view-comment/view-comment.component.html, src/app/applications/application-detail/decisions/decisions-tab-content.component.html, src/app/applications/application-detail/decisions/decisions-tab-content.component.scss, src/app/applications/application-detail/decisions/decisions-tab-content.component.ts, src/app/models/decision.ts, src/app/services/api.ts, src/app/services/application.service.ts, src/app/services/comment.service.ts, src/app/services/document.service.ts
PRC-153: identify remaining work
PRC-132: fix Offer Not Accepted status text
PRC-154: identify remaining work
NOBUG: don't display "no xxx found" while page loading
PRC-103: decision model, service and tab page
=> PRC-103, 132, 153, 154: implemented Decisions + incremental work/layout/etc

src/app/applications/application-detail/comments/comments-tab-content.component.scss, src/app/applications/application-detail/comments/view-comment/view-comment.component.html, src/app/applications/application-detail/comments/view-comment/view-comment.component.ts, src/app/applications/application-detail/decisions/decisions-tab-content.component.html, src/app/applications/application-list/application-list.component.scss, src/app/home/home.component.scss, src/app/map/main-map/main-map.component.scss, src/app/search/search.component.scss, src/app/services/api.ts, src/app/services/comment.service.ts, src/app/services/commentperiod.service.ts, src/app/services/document.service.ts, src/app/services/proponent.service.ts
NOBUG: fixed some property names
=> PRC-154: get documents by comment or decision (both ways)

src/app/applications/application-detail/application-detail.component.html
Note: wrong PRC number in commit.
=> PRC-150: used alternate router parameter so URL displays tab name

src/app/app.component.html, src/app/app.component.scss, src/app/app.component.ts, src/app/applications/application-list/application-list.component.scss, src/app/header/header.component.html, src/app/header/header.component.scss, src/app/header/header.component.ts, src/app/home/home.component.html, src/app/home/home.component.scss, src/assets/styles/components/badge.scss, src/assets/styles/components/feature-block.scss, src/assets/styles/layout.scss, src/assets/styles/themes/default.scss
- Fixed Alert Banner
- Updated application layout to support variable height banner for all pages
- Fixed / updated the home page layout / styling / structure
=> [PRC-229] UI Dev

src/app/app.component.ts, src/app/applications/application-detail/add-comment/add-comment.component.scss, src/app/applications/application-list/application-list.component.html, src/app/applications/application-list/application-list.component.ts, src/app/home/home.component.html, src/index.html
For details, see commit comments.
=>  PRC-320, PRC-323, PRC-316: refactored app list wrt filtering and map + comment height

src/app/applications/application-detail/add-comment/add-comment.component.scss, src/app/applications/application-detail/comments/view-comment/view-comment.component.scss
Includes merge conflict resolutions.
=> PRC-316: reduced Comment popup max height to better fit on Pixel 2, etc

src/app/application/add-comment/add-comment.component.html, src/app/applications/applications.module.ts, src/app/shared.module.ts
PRC-289: made Email or Phone required + made Comment textarea resizable + moved ngVar directive to shared module
PRC-155: added validation to Name, Location, Email and Phone
=> PRC289 + PRC155: Submit Comment form changes

src/app/application/add-comment/add-comment.component.html, src/app/application/add-comment/add-comment.component.scss, src/app/application/add-comment/file-upload/file-upload.component.scss
UI updates/modification requests.
- Set the default size of the comment textarea to 18.75rem (300px)
- Reduced the padding of the drag/drop target component
- Updated the font-size of the drag/drop target component
- Fixed whitespace in SCSS file.
=> [PRC-363] Submit Comment UI Updates

src/app/application/add-comment/add-comment.component.html, src/app/application/add-comment/add-comment.component.scss, src/app/application/add-comment/add-comment.component.ts, src/app/application/application.component.ts, src/app/application/commenting-tab/view-comment/view-comment.component.scss, src/assets/styles/components/buttons.scss, src/assets/styles/components/form-elements.scss, src/assets/styles/components/modal.scss, src/assets/styles/themes/default.scss
Fixing issues with the Submit Comment Interface on smaller devices.
- Updated to use the ngbootstrap implementation of the modal window (correctly applies the selector to the body component, which provides correct scrolling behavior in the modal interface.
- Removed global modal styling from components and standardized in the modal component style sheet
- Added variables for modal styling
- Removed global form-bases selectors and styling from specific components and standardized in the form-control component style sheet
=> [PRC-316] Submit Comments in Mobile Fix

src/app/applications/applist-map/applist-map.component.ts, src/app/models/application.ts, src/app/services/application.service.ts, src/app/shared.module.ts, src/app/utils/drag-move.directive.spec.ts, src/app/utils/drag-move.directive.ts
I did not squash because these can be cherry-picked to master/beta independently.
=> PRC-441 + NOBUGs

src/app/applications/applist-filters/applist-filters.component.ts, src/app/header/header.component.html, src/app/home/home.component.html, src/app/models/application.ts, src/app/services/api.ts, src/app/services/application.service.ts
also updated some region names + other cleanup
=> PRC-441: implemented regions filter (and hard-coded SK)

src/app/applications/applist-filters/applist-filters.component.ts, src/app/applications/applist-list/applist-list.component.html
(not squashed because these are independent and could be cherry-picked separately)
=> PRC-441: fixed bug + fixed CP day format

src/app/applications/applist-filters/applist-filters.component.html
Adding missing gtm tags to the filter control
=> [PRC-338] Adding gtm class names to filters component

src/app/applications/applications.component.ts, src/app/applications/applist-filters/applist-filters.component.ts, src/app/applications/applist-list/applist-list.component.html, src/app/applications/applist-list/applist-list.component.ts, src/app/applications/applist-map/applist-map.component.html, src/app/applications/applist-map/applist-map.component.ts, src/app/services/application.service.ts, src/app/services/config.service.ts
NOBUG: moved applist options to config service + more profiling code + misc mapping cleanup
NOBUG: misc changes to support responsive list vs map and stored map properties + cleanup
NOBUG: fixed lint errors
=> NOBUG: misc map event and config changes

src/app/applications/applist-map/applist-map.component.scss, src/app/applications/applist-map/applist-map.component.ts
Implementing the initial pass of the newest design for the map popup interface.
=> [PRC-421] Map Popup Design Updates

src/app/applications/applist-filters/applist-filters.component.html, src/app/applications/applist-filters/applist-filters.component.scss, src/app/applications/applist-list/applist-list.component.html, src/app/applications/applist-list/applist-list.component.scss, src/app/applications/applist-list/applist-list.component.ts, src/app/applications/applist-map/applist-map.component.html, src/app/applications/applist-map/applist-map.component.scss, src/app/applications/applist-map/applist-map.component.ts, src/app/services/config.service.ts, src/assets/styles/components/form-elements.scss, src/assets/styles/layout/layout.scss, src/styles.scss
Refactor & update the map/list interfaces so they are fully responsive
Additional Fixes / Updates
- removed duplicated reference to the material icon styling (styles.scss)
- removed unused functionality list toggle functionality
- white-space fix on various SCSS files
- fixed an issue where the 'No Results' message did not appear when required
=> [PRC-398] Map/List Interface Responsive Design Updates

src/app/application/add-comment/add-comment.component.html, src/app/application/add-comment/add-comment.component.scss, src/app/applications/applications.module.ts, src/app/shared.module.ts
PRC-400: comment form validation + large checkbox
PRC-289: made email or phone required
PRC-155: add validation to email and phone
=> PRC-400: comment form validation + large checkbox

src/app/applications/applist-filters/applist-filters.component.html, src/app/applications/applist-filters/applist-filters.component.scss, src/app/applications/applist-list/applist-list.component.html, src/app/applications/applist-list/applist-list.component.scss, src/app/applications/applist-list/applist-list.component.ts, src/app/applications/applist-map/applist-map.component.html, src/app/applications/applist-map/applist-map.component.scss, src/app/applications/applist-map/applist-map.component.ts, src/app/services/config.service.ts, src/assets/styles/components/form-elements.scss, src/assets/styles/layout/layout.scss, src/styles.scss
This reverts commit 7b58dae932f9274734dacaeef7d4b902b9cb5a07, reversing
changes made to eb63b9e3ec5b1742a872ba398bf1abac43fb9ccf.
=> Revert "Merge pull request #235 from jeznorth/PRC-398"

src/app/app.module.ts, src/app/applications/applist-list/applist-list.component.ts, src/app/applications/applist-map/applist-map.component.html, src/app/applications/applist-map/applist-map.component.ts, src/app/services/application.service.ts, src/assets/styles/components/leaflet.scss, src/styles.scss
PRC-470: fixed leaflet.markercluster import
=> PRC-379: implemented clustering

src/app/applications/applications.component.ts, src/app/applications/applist-filters/applist-filters.component.ts, src/app/applications/applist-list/applist-list.component.html, src/app/applications/applist-list/applist-list.component.ts, src/app/applications/applist-map/applist-map.component.html, src/app/applications/applist-map/applist-map.component.ts, src/app/services/application.service.ts, src/app/services/config.service.ts
NOBUG: support for responsive list vs map
NOBUG: fixed lint errors
NOBUG: misc mapping cleanup
=> NOBUG: moved applist options and map properties to config service

src/app/applications/applist-map/applist-map.component.ts
Reverts bcgov/nrts-prc-public#262
=> Revert "PRC-483: updated zoom on map resize to maintain scale"

src/app/app.module.ts, src/app/applications/app-detail-popup/app-detail-popup.component.html, src/app/applications/app-detail-popup/app-detail-popup.component.scss, src/app/applications/app-detail-popup/app-detail-popup.component.spec.ts, src/app/applications/app-detail-popup/app-detail-popup.component.ts, src/app/applications/applications.module.ts, src/app/applications/applist-map/applist-map.component.scss, src/app/applications/applist-map/applist-map.component.ts
Added a new component for the Application Map Popup interface (separating it from the Application Map Component)
- Added ConfigService
- Added CustomCompileService (needed to render new template)
- Added markup/styling to address client names being rendered in all caps
=> [PRC-479] Create Template for Application Map Popup

src/app/app.component.html, src/app/app.component.scss, src/app/app.component.ts
Removed the 'Alpha' banner alert message markup / js / related styling
=> [PRC-391] Remove Alpha Banner

src/assets/styles/components/buttons.scss, src/assets/styles/components/hero-banner.scss
Whitespace / spacing fixes for various SCSS files
=> [WS] Fix whitepsace on various SCSS files

src/app/application/application-tab/application-tab.component.ts, src/app/application/application.component.html, src/app/application/application.component.ts, src/app/application/commenting-tab/commenting-tab.component.html, src/app/application/commenting-tab/commenting-tab.component.ts, src/app/application/decisions-tab/decisions-tab.component.html, src/app/application/decisions-tab/decisions-tab.component.ts, src/app/applications/applications.component.html, src/app/applications/applications.component.ts, src/app/applications/applist-filters/applist-filters.component.ts, src/app/applications/applist-list/applist-list.component.html, src/app/applications/applist-map/applist-map.component.ts, src/app/models/search.ts, src/app/services/api.ts, src/app/services/application.service.ts, src/assets/styles/base/base.scss
PRC-481: paged app loading
PRC-495: async app loading
PRC-388: (partial) replaced map spinner with snackbar
NOBUG: added missing region filter code
NOBUG: initial app API filtering code
NOBUG: misc cleanup
=> PRC-481, PRC-495, PRC-388 (see details)

src/app/applications/applist-map/applist-map.component.ts
Reverts bcgov/nrts-prc-public#276
=> Revert "PRC-648: clean up marker actions"

src/app/application/application-tab/application-tab.component.html, src/app/application/application.component.html, src/app/application/commenting-tab/commenting-tab.component.html, src/app/application/decisions-tab/decisions-tab.component.html, src/app/applications/applications.component.html, src/app/applications/applications.component.ts, src/app/applications/applist-filters/applist-filters.component.html, src/app/applications/applist-filters/applist-filters.component.ts, src/app/applications/applist-list/applist-list.component.html, src/app/applications/applist-list/applist-list.component.scss, src/app/applications/applist-list/applist-list.component.ts, src/app/applications/applist-map/applist-map.component.scss, src/app/applications/applist-map/applist-map.component.ts, src/app/models/application.ts, src/app/services/application.service.ts, src/app/services/config.service.ts, src/assets/styles/components/spinner.scss, src/assets/styles/themes/default.scss
filter-map-list interactions
improved paging of queries
app list updates including Load More
only draw new apps during paging
removed automatic map resizing
=> PRC-461, PRC-586, PRC-514: (see details)

src/app/applications/app-detail-popup/app-detail-popup.component.html, src/app/applications/app-detail-popup/app-detail-popup.component.scss
Added ability to link to Application Details page from the map popup interface
=> [PRC-567] Go To Application Details from Map Popup

src/app/contact/contact.component.html, src/app/footer/footer.component.html, src/app/footer/footer.component.scss, src/app/home/home.component.html, src/assets/styles/layout/layout.scss
Content changes on the home and contact pages.
Additional fixes
- Cleaning up some styling to deal with the reduced size of footer on larger pages
- Tightened up the spacing in the footer component
=> [PRC-390] Update Home and Contact Page Content

src/app/header/header.component.scss
Removed some crazy-high z-index value on the header component which conflicted with the submit a comment modal.
=> [PRC-593] Fixing Header Issue with Modals

src/app/application/application.component.html, src/app/applications/app-detail-popup/app-detail-popup.component.html, src/app/applications/applist-filters/applist-filters.component.html, src/app/applications/applist-list/applist-list.component.html, src/app/applications/applist-map/applist-map.component.html, src/app/header/header.component.html
Various Content changes
[PRC-686] Change 'Disposition Transaction ID' and variations to 'Disposition Transaction'
[PRC-688] Change 'Crown Land' and variations to 'Crown land'
[PRC-690] Change 'Client' to 'Applicant'
=> [PRC-686] Update Content

src/app/home/home.component.html
Small text change on the homepage in the feedback section.
=> [PRC-673] Homepage Text Change

src/app/application/add-comment/add-comment.component.html
Add job title to the contact details in the Submit Comment Interface
=> [PRC-664] Adding Job Title to Contact Information

src/app/application/application.component.html, src/app/applications/app-detail-popup/app-detail-popup.component.html, src/app/applications/applist-filters/applist-filters.component.html, src/app/applications/applist-list/applist-list.component.html, src/app/contact/contact.component.html
Minor content changes and fixes
[PRC-686] Remove 'ID' from 'Disposition Transaction ID'
[PRC-686] Correct usage / spelling of 'Crown land file'
=> [PRC-710] Content Changes

src/app/applications/applist-filters/applist-filters.component.html
Changing 'Disposition Transaction ID' to 'Disposition Transaction'
=> [PRC-686] Text Change

src/app/home/home.component.html, src/assets/styles/components/hero-banner.scss
Minor text changes.
Additional Updates
- Fixed the breakpoint on the hero banner title from wrapping on wide viewports.
=> [PRC-726] Minor Content Changes

src/app/applications/app-detail-popup/app-detail-popup.component.html, src/app/applications/app-detail-popup/app-detail-popup.component.scss, src/app/applications/applist-map/applist-map.component.scss
Updating the map popup to better support smaller devices
=> [PRC-745] Popup Updates for Mobile

src/app/application/commenting-tab/commenting-tab.component.html, src/app/application/commenting-tab/view-comment/view-comment.component.html, src/app/models/application.ts, src/app/models/client.ts, src/app/models/comment.ts, src/app/models/commentperiod.ts, src/app/models/decision.ts, src/app/models/feature.ts, src/app/models/organization.ts, src/app/models/search.ts, src/app/models/user.ts, src/app/services/api.ts, src/app/services/application.service.ts, src/app/services/comment.service.ts, src/app/services/decision.service.ts, src/app/services/document.service.ts, src/app/services/organization.service.ts, src/app/services/search.service.ts
- updated code that referenced obsolete tags property
- initialized/assigned object dates correctly
- initialized/assigned sub-objects correctly
- alphabetized a model's properties for easier-to-understand code
- moved multi-line handling code to models for simpler code
- deleted obsolete imports
- deleted obsolete code properties
- updated SearchResults and SearchTerms same as Admin project
- changed getCountApplications() to use head verb same as Admin project
=> PRC-852: model cleanup

src/app/app.component.spec.ts, src/app/application/add-comment/add-comment.component.spec.ts, src/app/application/application-tab/application-tab.component.spec.ts, src/app/application/application.component.spec.ts, src/app/application/commenting-tab/commenting-tab.component.spec.ts, src/app/application/commenting-tab/view-comment/view-comment.component.spec.ts, src/app/application/decisions-tab/decisions-tab.component.spec.ts, src/app/applications/app-detail-popup/app-detail-popup.component.spec.ts, src/app/applications/applications.component.spec.ts, src/app/applications/applist-filters/applist-filters.component.spec.ts, src/app/applications/applist-list/applist-list.component.spec.ts, src/app/applications/applist-map/applist-map.component.spec.ts, src/app/date-input/date-input.component.spec.ts, src/app/footer/footer.component.spec.ts, src/app/header/header.component.spec.ts, src/app/home/home.component.spec.ts, src/app/services/application.service.spec.ts, src/app/services/comment.service.spec.ts, src/app/services/commentperiod.service.spec.ts, src/app/services/commentperiod.service.ts, src/app/utils/drag-move.directive.spec.ts, src/app/utils/ng-var.directive.spec.ts
Fixing more test dependencies, writing unit tests to capture behavior in certain services.
=> Test suite improvements

src/app/application/application-resolver.service.spec.ts, src/app/application/application-tab/application-tab.component.spec.ts, src/app/application/commenting-tab/commenting-tab.component.spec.ts, src/app/application/decisions-tab/decisions-tab.component.spec.ts, src/app/applications/app-detail-popup/app-detail-popup.component.spec.ts, src/app/services/application.service.spec.ts, src/app/services/comment.service.spec.ts, src/app/services/commentperiod.service.spec.ts, src/app/services/decision.service.spec.ts, src/app/services/document.service.spec.ts, src/app/services/feature.service.spec.ts, src/app/services/search.service.spec.ts, src/app/spec/helpers.ts
- Adding more tests to application service
- Add tests for decision and commenting service
- Adding tests for component routing
=> Adding further test coverage

src/app/applications/details-panel/details-panel.component.html, src/app/applications/details-panel/details-panel.component.scss
Fixing a few layout issues in various interfaces
Application Details
- Fixed an issue where the title panel (Applicant name and purpose) were not a part of the scroll area
Main Navigation
- Fixed an issue where the main navigation items were sizing incorrectly
=> [UI-Fixes] Fixing Navigation Item Sizing Issue for IE

src/app/applications/explore-panel/explore-panel.component.html, src/assets/styles/components/form-elements.scss
Fixing the help links in the Explore Panel
=> [UI-Fixes] Fixing Help Link in Explore Panel

src/app/comment-modal/comment-modal.component.html
Jira: https://bcnrds.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=PRC&modal=detail&selectedIssue=PRC-975
=> PRC-975: update email regex to allow dashes

src/assets/styles/components/form-elements.scss, src/assets/styles/themes/default.scss
Fixing the validation messages that do not appear in the comment form.
- Minor styling clean-up
=> [PRC-991] Fix Validation Messages

src/app/file-upload/file-upload.component.html, src/app/file-upload/file-upload.component.scss, src/app/file-upload/file-upload.component.ts, src/assets/styles/themes/default.scss
=> PRC-1012: fixed file input handling

src/app/file-upload/file-upload.component.html, src/app/file-upload/file-upload.component.scss, src/app/file-upload/file-upload.component.ts, src/assets/styles/components/buttons.scss, src/assets/styles/components/doc-list.scss, src/assets/styles/themes/default.scss, src/styles.scss
(re-PRed as Jer and I did some additional UI cleanup to the list styles... but no functionality change so I'm just going to merge it right away)
=> PRC-1012: fix for file input handling + UI cleanup

src/app/applications/app-map/marker-popup/marker-popup.component.scss, src/app/applications/applications.component.html, src/app/applications/applications.component.scss, src/app/applications/details-panel/details-panel.component.html, src/app/applications/details-panel/details-panel.component.scss, src/app/applications/explore-panel/date-input/date-input.component.scss, src/app/applications/explore-panel/explore-panel.component.scss, src/assets/styles/layout/layout.scss, src/index.html
Various UI Cleanup including:
- Tightened up the vertical spacing on the marker popup-component
- Standardized styling between application details title panel and marker information (client name / application purpose)
- Updated naming conventions in the Application Results Component and Details Component (title-case)
- Tightened up the vertical spacing between sections in the Details Component
- Updated the date input component (consistent layout/experience from mobile to desktop)
- Added meta information to allow application to be served as home screen on mobile devices
- Added meta description
=> UI-Cleanup

src/app/applications/applications.component.scss, src/app/applications/details-panel/details-panel.component.html, src/app/applications/details-panel/details-panel.component.scss, src/app/comment-modal/comment-modal.component.ts, src/app/file-upload/file-upload.component.html, src/app/header/header.component.scss, src/assets/styles/components/doc-list.scss
Consolidated the document list styling
Additional Updates
- Streamlined header styling (border-width)
- Updated the confirm message for the comment interface
=> [UI-Cleanup] UI / Code Cleanup

src/app/about/about.component.html
Noticed this as I was exploring your beautiful UI — kudos!!
=> NOBUG: fix spelling typo
